### ISSUE TITLE
Search filtering

### ISSUE THREAD

**Issue by longrunningprocess** [presciencelabs/tabitha-ontology#33] opened 2024-04-22 16:44 UTC
Craig asked for some filtering, e.g., show me all the nouns, or limit my search results to Nouns only.

_Originally posted by @longrunningprocess in https://github.com/presciencelabs/tabitha-ontology/issues/11#issuecomment-1939708915_

**Comment by craigp-atw** [comment] 2024-07-03 17:22
duplicate of #44

**Closed by craigp-atw** 2024-07-03 17:22 UTC
